spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
debug: true


